# Using Python for Research Homework: Week 4, Case Study 3

Homophily is a property of networks.  Homophily occurs when nodes that are neighbors in a network also share a characteristic more often than nodes that are not network neighbors.  In this case study, we will investigate homophily of several characteristics of individuals connected in social networks in rural India.

### Exercise 1
In Exercise 1, we will calculate the chance homophily for an arbitrary characteristic. Homophily is the proportion of edges in the network whose constituent nodes share that characteristic.

How much homophily do we expect by chance? If characteristics are distributed completely randomly, the probability that two nodes \(x\) and \(y\) share characteristic \(a\) is the probability both nodes have characteristic \(a\) , which is the marginal probability of \(a\) squared. The total probability that nodes \(x\) and \(y\) share their characteristic is therefore the sum of the square of the marginal probabilities of each characteristic in the network.

<strong>Instructions</strong>
<ul><li>Create a function <code>marginal_prob</code> that takes a dictionary <code>chars</code> with personal IDs as keys and characteristics as values; it should return a dictionary with characteristics as keys and their marginal probability (frequency of occurence of a characteristic divided by the sum of frequencies of each characteristic) as values.</li>
<li>Create a function <code>chance_homophily(chars)</code> that takes a dictionary <code>chars</code> defined as above and computes the chance homophily (homophily due to chance alone) for that characteristic.</li>
<li>A sample of three peoples' favorite colors is given in <code>favorite_colors</code>. Use your function to compute the chance homophily in this group, and store it as <code>color_homophily</code>.</li>
<li>Print <code>color_homophily</code>.</li></ul>

In [9]:
from collections import Counter
import numpy as np


def chance_homophily(chars):
    # Enter code here!
    chars_counts_dict = Counter(chars.values())
    chars_counts = np.array(list(chars_counts_dict.values()))
    chars_props  = chars_counts / sum(chars_counts)
    return sum(chars_props**2)

favorite_colors = {
    "ankit":  "red",
    "xiaoyu": "blue",
    "mary":   "blue"
}

color_homophily = chance_homophily(favorite_colors)
print(color_homophily)

0.5555555555555556

### Exercise 2

In the remaining exercises, we will calculate actual homophily in these village and compare the obtained values to those obtained by chance. In this exercise, we subset the data into individual villages and store them.

#### Instructions 

- `individual_characteristics.dta` contains several characteristics for each individual in the dataset such as age, religion, and caste. Use the `pandas` library to read in and store these characteristics as a dataframe called `df`.
- Store separate datasets for individuals belonging to Villages 1 and 2 as `df1` and `df2`, respectively.
- Note that some attributes may be missing for some individuals. In this case study, we will ignore rows of data where some column information is missing.
- Use the head method to display the first few entries of `df1`.

In [1]:
import pandas as pd

df  = pd.read_csv("https://courses.edx.org/asset-v1:HarvardX+PH526x+2T2019+type@asset+block@individual_characteristics.csv", low_memory=False, index_col=0)
df1 = df[(df['village']==1)]
df2 = df[(df['village']==2)]
df1.head()

,village,adjmatrix_key,pid,hhid,resp_id,resp_gend,resp_status,age,religion,caste,...,privategovt,work_outside,work_outside_freq,shgparticipate,shg_no,savings,savings_no,electioncard,rationcard,rationcard_colour
0,1,5,100201,1002,1,1,Head of Household,38,HINDUISM,OBC,...,PRIVATE BUSINESS,Yes,0.0,No,NaN,No,NaN,Yes,Yes,GREEN
1,1,6,100202,1002,2,2,Spouse of Head of Household,27,HINDUISM,OBC,...,NaN,NaN,NaN,No,NaN,No,NaN,Yes,Yes,GREEN
2,1,23,100601,1006,1,1,Head of Household,29,HINDUISM,OBC,...,OTHER LAND,No,NaN,No,NaN,No,NaN,Yes,Yes,GREEN
3,1,24,100602,1006,2,2,Spouse of Head of Household,24,HINDUISM,OBC,...,PRIVATE BUSINESS,No,NaN,Yes,1.0,Yes,1.0,Yes,No,NaN
4,1,27,100701,1007,1,1,Head of Household,58,HINDUISM,OBC,...,OTHER LAND,No,NaN,No,NaN,No,NaN,Yes,Yes,GREEN

### Exercise 3 

In this exercise, we define a few dictionaries that enable us to look up the sex, caste, and religion of members of each village by personal ID. For Villages 1 and 2, their personal IDs are stored as `pid`.

#### Instructions 
- Define dictionaries with personal IDs as keys and a given covariate for that individual as values. Complete this for the sex, caste, and religion covariates, for Villages 1 and 2.
- For Village 1, store these dictionaries into variables named `sex1`, `caste1`, and `religion1`.
- For Village 2, store these dictionaries into variables named `sex2`, `caste2`, and `religion2`.

In [3]:
sex1      = dict(zip(df1.pid, df1.resp_gend))
caste1    = dict(zip(df1.pid, df1.caste))
religion1 = dict(zip(df1.pid, df1.religion))


# Continue for df2 as well.
sex2      = dict(zip(df2.pid, df2.resp_gend))
caste2    = dict(zip(df2.pid, df2.caste))
religion2 = dict(zip(df2.pid, df2.religion))

In [4]:
caste2

{200101: 'GENERAL',
 200201: 'GENERAL',
 200202: 'GENERAL',
 200401: 'GENERAL',
 200402: 'GENERAL',
 200601: 'GENERAL',
 200602: 'GENERAL',
 200603: 'GENERAL',
 200604: 'GENERAL',
 200901: 'GENERAL',
 200902: 'OBC',
 201001: 'GENERAL',
 201002: 'GENERAL',
 201102: 'GENERAL',
 201103: 'GENERAL',
 201201: 'GENERAL',
 201202: 'GENERAL',
 201203: 'GENERAL',
 201204: 'GENERAL',
 201205: 'GENERAL',
 201206: 'GENERAL',
 201301: 'GENERAL',
 201302: 'GENERAL',
 201501: 'OBC',
 201502: 'OBC',
 201601: 'GENERAL',
 201602: 'GENERAL',
 201801: 'GENERAL',
 201802: 'GENERAL',
 202001: 'GENERAL',
 202002: 'GENERAL',
 202401: 'GENERAL',
 202402: 'GENERAL',
 202501: 'GENERAL',
 202502: 'GENERAL',
 202601: 'GENERAL',
 202602: 'GENERAL',
 202801: 'GENERAL',
 202802: 'OBC',
 202803: 'OBC',
 203201: 'GENERAL',
 203202: 'GENERAL',
 203301: 'GENERAL',
 203302: 'GENERAL',
 203601: 'OBC',
 203602: 'OBC',
 203701: 'GENERAL',
 203702: 'GENERAL',
 204501: 'SCHEDULED CASTE',
 204502: 'SCHEDULED CASTE',
 204504: 'SCHEDULED CASTE',
 204601: 'SCHEDULED CASTE',
 204602: 'SCHEDULED CASTE',
 205001: 'SCHEDULED CASTE',
 205002: 'SCHEDULED CASTE',
 205004: 'SCHEDULED CASTE',
 205101: 'SCHEDULED CASTE',
 205102: 'SCHEDULED CASTE',
 205301: 'SCHEDULED CASTE',
 205302: 'SCHEDULED CASTE',
 205401: 'SCHEDULED CASTE',
 205402: 'SCHEDULED CASTE',
 205501: 'SCHEDULED CASTE',
 205502: 'SCHEDULED CASTE',
 205601: 'SCHEDULED CASTE',
 205602: 'SCHEDULED CASTE',
 206001: 'SCHEDULED CASTE',
 206002: 'SCHEDULED CASTE',
 206201: 'SCHEDULED CASTE',
 206202: 'SCHEDULED CASTE',
 206601: 'SCHEDULED CASTE',
 206602: 'SCHEDULED CASTE',
 206901: 'SCHEDULED CASTE',
 206902: 'SCHEDULED CASTE',
 206903: 'SCHEDULED CASTE',
 206904: 'SCHEDULED CASTE',
 206908: 'SCHEDULED CASTE',
 206909: 'SCHEDULED CASTE',
 207101: 'SCHEDULED CASTE',
 207102: 'SCHEDULED CASTE',
 207401: 'SCHEDULED CASTE',
 207402: 'SCHEDULED CASTE',
 207403: 'SCHEDULED CASTE',
 207801: 'SCHEDULED CASTE',
 207802: 'SCHEDULED CASTE',
 208102: 'SCHEDULED CASTE',
 208201: 'SCHEDULED CASTE',
 208202: 'SCHEDULED CASTE',
 208301: 'SCHEDULED CASTE',
 208302: 'SCHEDULED CASTE',
 208401: 'SCHEDULED CASTE',
 208402: 'SCHEDULED CASTE',
 208501: 'SCHEDULED CASTE',
 208502: 'SCHEDULED CASTE',
 208503: 'SCHEDULED CASTE',
 208601: 'SCHEDULED CASTE',
 208602: 'SCHEDULED CASTE',
 208603: 'SCHEDULED CASTE',
 208701: 'SCHEDULED CASTE',
 208801: 'SCHEDULED CASTE',
 208802: 'SCHEDULED CASTE',
 208803: 'SCHEDULED CASTE',
 208804: 'SCHEDULED CASTE',
 208805: 'SCHEDULED CASTE',
 208901: 'SCHEDULED CASTE',
 208902: 'SCHEDULED CASTE',
 209301: 'SCHEDULED CASTE',
 209302: 'SCHEDULED CASTE',
 209501: 'SCHEDULED CASTE',
 209502: 'SCHEDULED CASTE',
 209503: 'SCHEDULED CASTE',
 209504: 'SCHEDULED CASTE',
 209601: 'SCHEDULED CASTE',
 209602: 'SCHEDULED CASTE',
 209801: 'SCHEDULED CASTE',
 209802: 'SCHEDULED CASTE',
 209803: 'SCHEDULED CASTE',
 209804: 'SCHEDULED CASTE',
 209805: 'OBC',
 210401: 'OBC',
 210402: 'OBC',
 210403: 'OBC',
 210404: 'OBC',
 210501: 'OBC',
 210502: 'OBC',
 210505: 'OBC',
 210601: 'GENERAL',
 210602: 'GENERAL',
 210701: 'GENERAL',
 210702: 'GENERAL',
 210901: 'OBC',
 210902: 'GENERAL',
 211101: 'GENERAL',
 211102: 'GENERAL',
 211801: 'GENERAL',
 211802: 'OBC',
 211805: 'GENERAL',
 211901: 'GENERAL',
 211902: 'GENERAL',
 211903: 'GENERAL',
 211904: 'GENERAL',
 212101: 'GENERAL',
 212102: 'GENERAL',
 212301: 'GENERAL',
 212302: 'GENERAL',
 212303: 'GENERAL',
 212304: 'GENERAL',
 212306: 'GENERAL',
 212307: 'GENERAL',
 212401: 'GENERAL',
 212402: 'GENERAL',
 213001: 'GENERAL',
 213002: 'GENERAL',
 213003: 'GENERAL',
 213004: 'GENERAL',
 213101: 'GENERAL',
 213102: 'GENERAL',
 213701: 'GENERAL',
 213702: 'GENERAL',
 213801: 'GENERAL',
 213802: 'OBC',
 214101: 'GENERAL',
 214102: 'GENERAL',
 214103: 'GENERAL',
 214104: 'GENERAL',
 214201: 'GENERAL',
 214202: 'GENERAL',
 214203: 'GENERAL',
 214206: 'GENERAL',
 214401: 'GENERAL',
 214402: 'GENERAL',
 214501: 'GENERAL',
 214502: 'GENERAL',
 214503: 'GENERAL',
 214504: 'GENERAL',
 214901: 'GENERAL',
 214902: 'GENERAL',
 215401: 'GENERAL',
 215402: 'GENERAL',
 215701: 'GENERAL',
 215702: 'GENERAL',
 215703: 'GENERAL',
 215704: 'GENERAL',
 215901: 'GENERAL',
 215902: 'GENERAL',
 216101: 'GENERAL',
 216102: 'OBC',
 216401: 'OBC',
 216402: 'GENERAL',
 216403: 'GENERAL',
 216404: 'GENERAL',
 216701: 'GENERAL',
 216702: 'GENERAL',
 216801: 'GENERAL',
 216802: 'GENERAL',
 216803: 'OBC',
 216804: 'OBC',
 216901: 'GENERAL',
 216902: 'GENERAL',
 216903: 'GENERAL',
 216904: 'OBC',
 216905: 'GENERAL',
 216906: 'GENERAL'}

### Exercise 4

In this exercise, we will print the chance homophily of several characteristics of Villages 1 and 2. 

#### Instructions 
-  Use `chance_homophily` to compute the chance homophily for sex, caste, and religion In Villages 1 and 2. Is the chance homophily for any attribute very high for either village?

In [10]:
# Enter your code here.
#village 1
print("Village 1 chance of same sex:", chance_homophily(sex1))
print("Village 1 chance of same castel:", chance_homophily(caste1))
print("Village 1 chance of same religion:", chance_homophily(religion1))
#village 2
print("Village 2 chance of same sex:", chance_homophily(sex2))
print("Village 2 chance of same castle:", chance_homophily(caste2))
print("Village 2 chance of same relegion:", chance_homophily(religion2))

Village 1 chance of same sex: 0.5027299861680701
Village 1 chance of same castel: 0.6741488509791551
Village 1 chance of same religion: 0.9804896988521925
Village 2 chance of same sex: 0.5005945303210464
Village 2 chance of same castle: 0.425368244800893
Village 2 chance of same relegion: 1.0

### Exercise 5

In this exercise, we will create a function that computes the observed homophily given a village and characteristic.

#### Instructions 
- Complete the function `homophily()`, which takes a network `G`, a dictionary of node characteristics `chars`, and node IDs `IDs`. For each node pair, determine whether a tie exists between them, as well as whether they share a characteristic. The total count of these is `num_ties` and `num_same_ties`, respectively, and their ratio is the homophily of chars in `G`. Complete the function by choosing where to increment `num_same_ties` and `num_ties`.

In [25]:
def homophily(G, chars, IDs):
    """
    Given a network G, a dict of characteristics chars for node IDs,
    and dict of node IDs for each node in the network,
    find the homophily of the network.
    """
    num_same_ties, num_ties = 0, 0
    for n1 in G.nodes():
        for n2 in G.nodes():
            if n1 > n2:   # do not double-count edges!
                if IDs[n1] in chars and IDs[n2] in chars:
                    if G.has_edge(n1, n2):
                        # Should `num_ties` be incremented?  What about `num_same_ties`?
                        num_ties += 1
                        #num_same_ties = 0
                        if chars[IDs[n1]] == chars[IDs[n2]]:
                            # Should `num_ties` be incremented?  What about `num_same_ties`?
                            num_same_ties += 1
                            num_ties = 0
    return (num_same_ties / num_ties)

### Exercise 6

In this exercise, we will obtain the personal IDs for Villages 1 and 2. These will be used in the next exercise to calculate homophily for these villages.

#### Instructions 
- In this dataset, each individual has a personal ID, or PID, stored in `key_vilno_1.csv` and `key_vilno_2.csv` for villages 1 and 2, respectively. `data_filepath1` and `data_filepath2` contain the URLs to the datasets used in this exercise. Use `pd.read_csv` to read in and store `key_vilno_1.csv` and `key_vilno_2.csv` as `pid1` and `pid2` respectively.

In [26]:
data_filepath1 = "https://courses.edx.org/asset-v1:HarvardX+PH526x+2T2019+type@asset+block@key_vilno_1.csv"
data_filepath2 = "https://courses.edx.org/asset-v1:HarvardX+PH526x+2T2019+type@asset+block@key_vilno_2.csv"

# Enter code here!
pid1 = pd.read_csv(data_filepath1)
pid2 = pd.read_csv(data_filepath2)

In [27]:
pid1[0:101]

     Unnamed: 0       0
0             0  100101
1             1  100102
2             2  100103
3             3  100104
4             4  100201
..          ...     ...
96           96  102201
97           97  102202
98           98  102203
99           99  102204
100         100  102205

[101 rows x 2 columns]

In [28]:
pid1

     Unnamed: 0       0
0             0  100101
1             1  100102
2             2  100103
3             3  100104
4             4  100201
..          ...     ...
838         838  118202
839         839  118301
840         840  118302
841         841  118303
842         842  118304

[843 rows x 2 columns]

### Exercise 7

In this exercise, we will compute the homophily of several network characteristics for Villages 1 and 2 and compare them to homophily due to chance alone. The networks for these villages have been stored as networkx graph objects `G1` and `G2`.

#### Instructions 

- Use your `homophily()` function to compute the observed homophily for sex, caste, and religion in Villages 1 and 2. Print all six values.
- Use the `chance_homophily()` to compare these values to chance homophily. Are these values higher or lower than that expected by chance?

In [31]:
import networkx as nx
A1 = np.array(pd.read_csv("https://courses.edx.org/asset-v1:HarvardX+PH526x+2T2019+type@asset+block@adj_allVillageRelationships_vilno1.csv", index_col=0))
A2 = np.array(pd.read_csv("https://courses.edx.org/asset-v1:HarvardX+PH526x+2T2019+type@asset+block@adj_allVillageRelationships_vilno2.csv", index_col=0))
G1 = nx.to_networkx_graph(A1)
G2 = nx.to_networkx_graph(A2)

pid1 = pd.read_csv(data_filepath1, dtype=int)['0'].to_dict()
pid2 = pd.read_csv(data_filepath2, dtype=int)['0'].to_dict()

# Enter your code here!
print("Village 1 observed proportion of same sex:", homophily(G1, sex1, pid1))
#print("Village 1 observed proportion of same caste:", homophily(G1, caste1, pid1))

#print("Village 1 observed proportion of same relegion:", homophily(G1, religion1, pid1))

# print("Village 2 observed proportion of same sex:", homophily(G2, sex2, pid2))
# print("Village 2 observed proportion of same caste:", homophily(G2, caste2, pid2))
# print("Village 2 observed proportion of same religion:", homophily(G2, religion2 , pid2))

Village 1 observed proportion of same sex: 575.0